// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gsxhnd/jaha/server/db"
	"github.com/gsxhnd/jaha/server/handler"
	"github.com/gsxhnd/jaha/server/middleware"
	"github.com/gsxhnd/jaha/server/router"
	"github.com/gsxhnd/jaha/server/service"
	"github.com/gsxhnd/jaha/server/storage"
	"github.com/gsxhnd/jaha/utils"
)

// Injectors from wire.go:

func InitApp() (*Application, error) {
	config, err := utils.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := utils.NewLogger(config)
	middlewareMiddleware := middleware.NewMiddleware(logger)
	driver, err := db.NewDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	storageStorage, err := storage.NewStorage(config)
	if err != nil {
		return nil, err
	}
	pingService := service.NewPingService(logger, driver, storageStorage)
	pingHandler := handler.NewPingHandler(pingService)
	movieService := service.NewMovieService(logger, driver)
	validate := utils.NewValidator()
	movieHandler := handler.NewMovieHandler(movieService, validate, storageStorage, logger)
	movieActorService := service.NewMovieActorService(logger, driver)
	movieActorHandler := handler.NewMovieActorHandler(movieActorService, validate, logger)
	movieTagService := service.NewMovieTagService(logger, driver)
	movieTagHandler := handler.NewMovieTagHandler(movieTagService, validate, logger)
	actorService := service.NewActorService(logger, driver)
	actorHandler := handler.NewActorHandler(actorService, validate, logger)
	imageHandler := handler.NewImageHandler(validate, storageStorage, logger)
	tagService := service.NewTagService(logger, driver)
	tagHandler := handler.NewTagHandler(tagService, validate, logger)
	animeService := service.NewAnimeService(logger, driver)
	animeHandler := handler.NewAnimeHandler(animeService, validate, logger)
	handlerHandler := handler.Handler{
		PingHandler:      pingHandler,
		MovieHandler:     movieHandler,
		MovieActorHandle: movieActorHandler,
		MovieTagHandler:  movieTagHandler,
		ActorHandler:     actorHandler,
		ImageHandler:     imageHandler,
		TagHandler:       tagHandler,
		AnimeHandler:     animeHandler,
	}
	routerRouter, err := router.NewRouter(config, logger, middlewareMiddleware, handlerHandler)
	if err != nil {
		return nil, err
	}
	application := NewApplication(routerRouter)
	return application, nil
}
